cache:
  directories:
    - '$HOME/.composer/cache'
jobs:
  include:
    - stage: 'php-tests'
      name: 'PHPUnit tests'
      language: php
      php:
        - 7.1
      before_install:
        - openssl aes-256-cbc -K $encrypted_801c70028c9b_key -iv $encrypted_801c70028c9b_iv
          -in id_rsa.enc -out id_rsa -d
        - phpenv config-rm xdebug.ini || true
        - travis_retry composer self-update
      install:
        - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
      script: vendor/bin/phpunit
    - stage: 'js-tests'
      name: 'Jest tests'
      language: node_js
      node_js:
        - 'lts/*'
      before_install:
        - openssl aes-256-cbc -K $encrypted_801c70028c9b_key -iv $encrypted_801c70028c9b_iv
          -in id_rsa.enc -out id_rsa -d
      install:
        - travis_retry cd frontend && npm install
      script: npm run
